### ISSUE TITLE
playbook not setting up django-configurations properly

### ISSUE THREAD

**Issue by codersquid** [pyvideo/richard-ansible#5]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/srv/pyvideo/richard/src/richard/config/settings.py", line 352, in <module>
    class Testing(Base):
  File "/usr/local/lib/python2.7/dist-packages/configurations/base.py", line 30, in __new__
    raise ImproperlyConfigured(install_failure)
django.core.exceptions.ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use on
e of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/
[pid: 22432|app: 0|req: 3/3] 98.223.145.234 () {38 vars in 568 bytes} [Sat Mar  7 18:02:04 2015] GET / => generated 0 bytes in
 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by codersquid** [comment]
This is not an issue with the playbook, it is an issue with richard. see https://github.com/pyvideo/richard/pull/272
